
# Diccionario de municipios por departamento
municipios = {
    "alta_verapaz": [
        "Cobán", 
        "Santa Cruz Verapaz", 
        "San Cristóbal Verapaz", 
        "Tactic", 
        "Tamahú", 
        "San Miguel Tucurú", 
        "Panzós", 
        "Senahú", 
        "San Pedro Carchá", 
        "San Juan Chamelco", 
        "San Agustín Lanquín", 
        "Santa María Cahabón", 
        "Chisec", 
        "Chahal", 
        "Fray Bartolomé de las Casas", 
        "Santa Catalina La Tinta", 
        "Raxruhá"
    ],

    "baja_verapaz": [
        "Salamá",  # cabecera departamental
        "San Miguel Chicaj",
        "Rabinal",
        "Cubulco",
        "Granados",
        "Santa Cruz el Chol",
        "San Jerónimo",
        "Purulhá"
    ],
    "chimaltenango": [
        "Chimaltenango",  # cabecera departamental
        "San José Poaquil",
        "San Martín Jilotepeque",
        "San Juan Comalapa",
        "Santa Apolonia",
        "Tecpán",
        "Patzún",
        "San Miguel Pochuta",
        "Patzicía",
        "Santa Cruz Balanyá",
        "Acatenango",
        "San Pedro Yepocapa",
        "San Andrés Itzapa",
        "Parramos",
        "Zaragoza",
        "El Tejar"
    ],
    "chiquimula": [
        "Chiquimula",  # cabecera departamental
        "Jocotán",
        "Esquipulas",
        "Camotán",
        "Quezaltepeque",
        "Olopa",
        "Ipala",
        "San Juan Ermita",
        "Concepción Las Minas",
        "San Jacinto",
        "San José la Arada"
    ],
    "peten": [
        "Flores",  # cabecera departamental
        "San José",
        "San Benito",
        "San Andrés",
        "La Libertad",
        "San Francisco",
        "Santa Ana",
        "Dolores",
        "San Luis",
        "Sayaxché",
        "Melchor de Mencos",
        "Poptún"
    ],
    "el_progreso": [
        "El Jícaro",
        "Morazán",
        "San Agustín Acasaguastlán",
        "San Antonio La Paz",
        "San Cristóbal Acasaguastlán",
        "Sanarate",
        "Guastatoya",  # cabecera departamental
        "Sansare"
    ],
    "quiche": [
        "Santa Cruz del Quiché",  # cabecera departamental
        "Chiché",
        "Chinique",
        "Zacualpa",
        "Chajul",
        "Santo Tomás Chichicastenango",
        "Patzité",
        "San Antonio Ilotenango",
        "San Pedro Jocopilas",
        "Cunén",
        "San Juan Cotzal",
        "Santa María Joyabaj",
        "Santa María Nebaj",
        "San Andrés Sajcabajá",
        "Uspantán",
        "Sacapulas",
        "San Bartolomé Jocotenango",
        "Canillá",
        "Chicamán",
        "Ixcán",
        "Pachalum"
    ],

    "escuintla": [
        "Escuintla",  # cabecera departamental
        "Santa Lucía Cotzumalguapa",
        "La Democracia",
        "Siquinalá",
        "Masagua",
        "Tiquisate",
        "La Gomera",
        "Guazacapán",
        "San José",
        "Iztapa",
        "Palín",
        "San Vicente Pacaya",
        "Nueva Concepción"
    ],

    "guatemala": [
        "Santa Catarina Pinula",
        "San José Pinula",
        "Guatemala",  # cabecera departamental
        "San José del Golfo",
        "Palencia",
        "Chinautla",
        "San Pedro Ayampuc",
        "Mixco",
        "San Pedro Sacatapéquez",
        "San Juan Sacatepéquez",
        "Chuarrancho",
        "San Raymundo",
        "Fraijanes",
        "Amatitlán",
        "Villa Nueva",
        "Villa Canales",
        "San Miguel Petapa"
    ],

    "huehuetenango": [
        "Huehuetenango",  # cabecera departamental
        "Chiantla",
        "Malacatancito",
        "Cuilco",
        "Nentón",
        "San Pedro Necta",
        "Jacaltenango",
        "Soloma",
        "Ixtahuacán",
        "Santa Bárbara",
        "La Libertad",
        "La Democracia",
        "San Miguel Acatán",
        "San Rafael La Independencia",
        "Todos Santos Cuchumatán",
        "San Juan Atitlán",
        "Santa Eulalia",
        "San Mateo Ixtatán",
        "Colotenango",
        "San Sebastián Huehuetenango",
        "Tectitán",
        "Concepción Huista",
        "San Juan Ixcoy",
        "San Antonio Huista",
        "Santa Cruz Barillas",
        "San Sebastián Coatán",
        "Aguacatán",
        "San Rafael Petzal",
        "San Gaspar Ixchil",
        "Santiago Chimaltenango",
        "Santa Ana Huista"
    ],
    "izabal": [
        "Morales",
        "Los Amates",
        "Livingston",
        "El Estor",
        "Puerto Barrios"  # cabecera departamental
    ],
    "jalapa": [
        "Jalapa",  # cabecera departamental
        "San Pedro Pinula",
        "San Luis Jilotepeque",
        "San Manuel Chaparrón",
        "San Carlos Alzatate",
        "Monjas",
        "Mataquescuintla"
    ],
    "jutiapa": [
        "Jutiapa",  # cabecera departamental
        "El Progreso",
        "Santa Catarina Mita",
        "Agua Blanca",
        "Asunción Mita",
        "Yupiltepeque",
        "Atescatempa",
        "Jerez",
        "El Adelanto",
        "Zapotitlán",
        "Comapa",
        "Jalpatagua",
        "Conguaco",
        "Moyuta",
        "Pasaco",
        "Quesada"
    ],
    "quetzaltenango": [
        "Quetzaltenango",  # cabecera departamental
        "Salcajá",
        "San Juan Olintepeque",
        "San Carlos Sija",
        "Sibilia",
        "Cabricán",
        "Cajolá",
        "San Miguel Siguilá",
        "San Juan Ostuncalco",
        "San Mateo",
        "Concepción Chiquirichapa",
        "San Martín Sacatepéquez",
        "Almolonga",
        "Cantel",
        "Huitán",
        "Zunil",
        "Colomba Costa Cuca",
        "San Francisco La Unión",
        "El Palmar",
        "Coatepeque",
        "Génova",
        "Flores Costa Cuca",
        "La Esperanza",
        "Palestina de Los Altos"
    ],
    "retalhuleu": [
        "Retalhuleu",  # cabecera departamental
        "San Sebastián",
        "Santa Cruz Muluá",
        "San Martín Zapotitlán",
        "San Felipe",
        "San Andrés Villa Seca",
        "Champerico",
        "Nuevo San Carlos",
        "El Asintal"
    ],
    "sacatepequez": [
        "Antigua Guatemala",  # cabecera departamental
        "Jocotenango",
        "Pastores",
        "Sumpango",
        "Santo Domingo Xenacoj",
        "Santiago Sacatepéquez",
        "San Bartolomé Milpas Altas",
        "San Lucas Sacatepéquez",
        "Santa Lucía Milpas Altas",
        "Magdalena Milpas Altas",
        "Santa María de Jesús",
        "Ciudad Vieja",
        "San Miguel Dueñas",
        "San Juan Alotenango",
        "San Antonio Aguas Calientes",
        "Santa Catarina Barahona"
    ],
    "san_marcos": [
        "San Marcos",  # cabecera departamental
        "Ayutla",
        "Catarina",
        "Comitancillo",
        "Concepción Tutuapa",
        "El Quetzal",
        "El Rodeo",
        "El Tumblador",
        "Ixchiguán",
        "La Reforma",
        "Malacatán",
        "Nuevo Progreso",
        "Ocós",
        "Pajapita",
        "Esquipulas Palo Gordo",
        "San Antonio Sacatepéquez",
        "San Cristóbal Cucho",
        "San José Ojetenam",
        "San Lorenzo",
        "San Miguel Ixtahuacán",
        "San Pablo",
        "San Pedro Sacatepéquez",
        "San Rafael Pie de la Cuesta",
        "Sibinal",
        "Sipacapa",
        "Tacaná",
        "Tajumulco",
        "Tejutla",
        "Río Blanco",
        "La Blanca"
    ],
    "santa_rosa": [
        "Cuilapa",  # cabecera departamental
        "Casillas Santa Rosa",
        "Chiquimulilla",
        "Guazacapán",
        "Nueva Santa Rosa",
        "Oratorio",
        "Pueblo Nuevo Viñas",
        "San Juan Tecuaco",
        "San Rafael Las Flores",
        "Santa Cruz Naranjo",
        "Santa María Ixhuatán",
        "Santa Rosa de Lima",
        "Taxisco",
        "Barberena"
    ],
    "solola": [
        "Sololá",  # cabecera departamental
        "Concepción",
        "Nahualá",
        "Panajachel",
        "San Andrés Semetabaj",
        "San Antonio Palopó",
        "San José Chacayá",
        "San Juan La Laguna",
        "San Lucas Tolimán",
        "San Marcos La Laguna",
        "San Pablo La Laguna",
        "San Pedro La Laguna",
        "Santa Catarina Ixtahuacán",
        "Santa Catarina Palopó",
        "Santa Clara La Laguna",
        "Santa Cruz La Laguna",
        "Santa Lucía Utatlán",
        "Santa María Visitación",
        "Santiago Atitlán"
    ],
    "suchitepequez": [
        "Mazatenango",  # cabecera departamental
        "Cuyotenango",
        "San Francisco Zapotitlán",
        "San Bernardino",
        "San José El Ídolo",
        "Santo Domingo Suchitépequez",
        "San Lorenzo",
        "Samayac",
        "San Pablo Jocopilas",
        "San Antonio Suchitépequez",
        "San Miguel Panán",
        "San Gabriel",
        "Chicacao",
        "Patulul",
        "Santa Bárbara",
        "San Juan Bautista",
        "Santo Tomás La Unión",
        "Zunilito",
        "Pueblo Nuevo",
        "Río Bravo"
    ],
    "totonicapan": [
        "Totonicapán",  # cabecera departamental
        "San Cristóbal Totonicapán",
        "San Francisco El Alto",
        "San Andrés Xecul",
        "Momostenango",
        "Santa María Chiquimula",
        "Santa Lucía La Reforma",
        "San Bartolo"
    ],
    "zacapa": [
        "Zacapa",  # cabecera departamental
        "Cabañas",
        "Estanzuela",
        "Gualán",
        "Huité",
        "La Unión",
        "Río Hondo",
        "San Jorge",
        "San Diego",
        "Teculután",
        "Usumatlán"
    ],

}